#!/usr/bin/env python3
"""
Version bump script for MCP Switch.

Version format: MAJOR.MINOR.PATCH+BUILD
- MAJOR.MINOR.PATCH follows SemVer, bumped by --type argument
- BUILD is always incremented by 1 from current value (never skips, never resets)

Updates:
- pubspec.yaml  (version: x.y.z+n)
- lib/constants/version.dart  (appVersion, buildNumber)
"""
import os
import re
import argparse

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBSPEC_PATH = os.path.join(PROJECT_ROOT, 'pubspec.yaml')
VERSION_DART_PATH = os.path.join(PROJECT_ROOT, 'lib', 'constants', 'version.dart')


def parse_version(version_str):
    match = re.search(r'(\d+)\.(\d+)\.(\d+)(?:\+(\d+))?', version_str)
    if match:
        return {
            'major': int(match.group(1)),
            'minor': int(match.group(2)),
            'patch': int(match.group(3)),
            'build': int(match.group(4)) if match.group(4) else 0,
        }
    return None


def read_pubspec_version():
    with open(PUBSPEC_PATH, 'r') as f:
        for line in f:
            if line.strip().startswith('version:'):
                return line.split(':')[1].strip()
    return None


def update_pubspec(new_version):
    with open(PUBSPEC_PATH, 'r') as f:
        lines = f.readlines()
    with open(PUBSPEC_PATH, 'w') as f:
        for line in lines:
            if line.strip().startswith('version:'):
                f.write(f'version: {new_version}\n')
            else:
                f.write(line)
    print(f"Updated pubspec.yaml -> {new_version}")


def update_dart_constant(v):
    semver = f"{v['major']}.{v['minor']}.{v['patch']}"
    content = f"""// This file is generated by scripts/bump_version.py

const String appVersion = 'Version {semver} (Build {v['build']})';
const String buildNumber = '{v['build']}';
"""
    with open(VERSION_DART_PATH, 'w') as f:
        f.write(content)
    print(f"Updated version.dart -> Version {semver} (Build {v['build']})")


def main():
    parser = argparse.ArgumentParser(description='Bump version in pubspec.yaml')
    parser.add_argument('--type', choices=['major', 'minor', 'patch'], default='patch')
    args = parser.parse_args()

    version_str = read_pubspec_version()
    if not version_str:
        print("ERROR: Could not read version from pubspec.yaml")
        exit(1)

    current = parse_version(version_str)
    if not current:
        print(f"ERROR: Could not parse version '{version_str}'")
        exit(1)

    print(f"Current: {version_str}")

    major, minor, patch = current['major'], current['minor'], current['patch']
    build = current['build']

    if args.type == 'major':
        major += 1
        minor = 0
        patch = 0
    elif args.type == 'minor':
        minor += 1
        patch = 0
    else:
        patch += 1

    build += 1

    new_version = f"{major}.{minor}.{patch}+{build}"
    print(f"Bumping ({args.type}): {version_str} -> {new_version}")

    update_pubspec(new_version)
    update_dart_constant({'major': major, 'minor': minor, 'patch': patch, 'build': build})


if __name__ == "__main__":
    main()
